### ISSUE TITLE
The question about running on no-laravel-based framework

### ISSUE THREAD

**Issue by Zorion-Z** [AraneaDev/laravel-electrum#4]
Hi dear:
I met a trouble when i want to use this package in a no-laravel-based framework like **themosis**.
Does this tool must use in the develop-environment based on `laravel-framework`, and publish it's asset using `php artisan`? 
So, if i want to use it in other  framework?
Thank u a lot.

**Comment by AraneaDev** [comment]
Hi ... sorry for the late answer... been swamped with other stuff. It was written for Laravel. It uses  artisan to map all RPC commands.
